public class Admin {
    private Database db1;
    private int revenue;
    public Admin(Database db1) {
        this.db1 = db1;
        revenue=0;
    }

    public int getRevenue() {
        return revenue;
    }

    public void addToRevenue(int ToAdd){
        this.revenue+= ToAdd;
    }
    public Admin() {
    }

    public void InsertProdCat(String src, String prodname,int price,int number,int isProd){
        //raise a custom exception on the same product
        try {
            db1.insert(src,prodname,price,number,isProd,this);
        } catch (SameProductException e) {
            System.out.println(e.getMessage());
        }
    }

    public Product search(String product){
        try {
            return db1.search(product,this);
        } catch (NoProductException e) {
            System.out.println(e.getMessage());

        }
        return null;
    }

    public void delete(String path){
        try {
            db1.delete(path,this);
        } catch (NoProductException e) {
            System.out.println(e.getMessage());
        }
    }

    public void Modify(String NameOfProd,int newPrice,int newDataItems){
        try {
            db1.Modify(NameOfProd,newPrice,newDataItems,this);
        } catch (NoProductException e) {
            System.out.println(e.getMessage());
        }
    }

    public void exit()
    {
        System.out.println("Total revenue generated by Amacon: "+getRevenue());
    }
}
